#!/usr/bin/env python3
"""Derive rules/libraries/*.yaml: which algorithms each library's source provides.

For every release listed in tools/libraries.json this clones the tag, runs gangmu's own
CBOM scan over the library's source directories, and writes the algorithms found. The
claim is "the source contains this algorithm, enabled by default or not", measured with
the same patterns the CBOM scan uses -- not a reading of the library's documentation.

Each entry covers the version span from `introduced` up to `fixed`, and keeps only what both the first
and the last tag of the span contain, so an algorithm that arrived mid-span is left out.

    python tools/derive_libraries.py [--only mbedtls] [--keep DIR]
"""
import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

import yaml

from gangmu.cbom import cbom_roots, load_algo_roots, scan_cbom
from gangmu import __version__

HERE = Path(__file__).resolve().parent
RULES = HERE.parent / "rules"


def algorithms_in(root: Path, subdirs, algos):
    found = set()
    for sub in subdirs:
        folder = root / sub
        if folder.is_dir():
            result = scan_cbom(folder, binaries=False, algos=algos)
            found |= {a.algo.key for a in result.assets if not a.variant}
    return found


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="derive just this library file (e.g. mbedtls)")
    ap.add_argument("--keep", help="clone into this directory and keep the clones")
    args = ap.parse_args()
    spec = json.loads((HERE / "libraries.json").read_text())
    algos = load_algo_roots(cbom_roots([str(RULES)]))
    order = [a.key for a in algos.algos]
    for lib in spec["libraries"]:
        if args.only and lib["file"] != args.only:
            continue
        releases = []
        for rel in lib["releases"]:
            sets = []
            for tag in dict.fromkeys([rel["first"], rel["tag"]]):
                with tempfile.TemporaryDirectory() as tmp:
                    base = Path(args.keep or tmp)
                    dest = base / f"{lib['file']}-{tag}"
                    if not dest.exists():
                        subprocess.run(["git", "clone", "--quiet", "--depth", "1", "--branch",
                                        tag, lib["url"], str(dest)], check=True)
                    sets.append(algorithms_in(dest, lib["subdirs"], algos))
            keys = set.intersection(*sets)
            if not keys:
                print(f"{lib['name']} {rel['tag']}: no algorithm found, check subdirs",
                      file=sys.stderr)
                return 1
            releases.append({
                "introduced": rel["introduced"], "fixed": rel["fixed"],
                "algorithms": [k for k in order if k in keys],
                "source": f"{lib['url']} tags {rel['first']} and {rel['tag']} (intersection), scanned {', '.join(lib['subdirs'])}"})
            print(f"{lib['name']} {rel['tag']}: {len(keys)} algorithms", file=sys.stderr)
        out = RULES / "libraries" / f"{lib['file']}.yaml"
        out.parent.mkdir(exist_ok=True)
        header = (f"# Generated by tools/derive_libraries.py with gangmu {__version__}; "
                  "do not edit by hand.\n"
                  "# 'Provides' means the source contains the algorithm, enabled by default or not.\n")
        out.write_text(header + yaml.safe_dump(
            {"libraries": [{"rule": lib["rule"], "name": lib["name"], "releases": releases}]},
            allow_unicode=True, sort_keys=False, width=100, default_flow_style=None))
    return 0


if __name__ == "__main__":
    sys.exit(main())
